apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: phonebook
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:80/backend:v1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: localhost:8080
          - key: database-url
            path: .env